List<String> Bad = [
  """Is your dad a boxer? Because you're a knockout.""",
  """If you were a vegetable, you'd be a cute-cumber!""",
  """My heart's a rebel tattoo, inked with defiance and yours to decipher.""",
  """They say I'm a riddle, wrapped in an enigma, begging to be solved. Ready to unravel the mystery?""",
  """Forget fairytales, I'm the anti-hero with a devilish grin and a soft spot for you.""",
  """Sparks fly when I walk by, not just the good kind. Care to play with fire?""",
  """I'm the thorn in your rose, the twist in your tale. Want to see how the story unfolds?""",
  """They call me troublemaker, but maybe you need a little disruption in your perfectly planned life.""",
  """Forget angels, I'm the siren with a whiskey voice and a melody just for you.""",
  """My reputation's wilder than a desert wind, but maybe you need a storm to chase away the dust.""",
  """They say I'm an open book, but the best chapters are hidden between the lines. Want to peek inside?""",
  """Danger is my middle name, but with you, I might just learn to play nice (emphasis on might).""",
  """They say I'm trouble, but maybe you need a little chaos in your life.""",
  """I'm the dark side of the moon, baby, full of hidden beauty and a few bumps along the way.""",
  """Forget angels, I'm the fallen one. Want to see how far we can tumble together?""",
  """My reputation precedes me, like a good plot twist. Are you up for the ending?""",
  """They call me bad news, but maybe good company cancels that out, right?""",
  """I'm the storm in your teacup, the hurricane in your hair. Ready to get a little wild?""",
  """Forget butterflies, I'm the firecracker that sets your soul ablaze (figuratively, of course).""",
  """They say I'm a bad habit, but maybe the best ones are hard to break.""",
  """Danger zone? More like adventure zone. Buckle up, it's gonna be a bumpy ride.""",
  """I'm the forbidden fruit, the one they warned you about. Want to take a bite anyway?"""
  """Do you have a map? Because I keep getting lost in your eyes, and I'm not complaining.""",
  """If beauty was a crime, you'd be serving a life sentence.""",
  """Is your name Google? Because you've got everything I've been searching for.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Excuse me, but I think you dropped something: my jaw.""",
  """Are you a parking ticket? Because you've got 'fine' written all over you.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If beauty were time, you'd be an eternity.""",
  """Are you a troublemaker? Because you've got mischief in those eyes.""",
  """Did it hurt when you fell from heaven? Because you look devilishly good.""",
  """Is your name Wi-Fi? Because I'm really feeling a connection.""",
  """Do you have a mirror in your pocket? Because I can see myself in your pants.""",
  """Excuse me, but I think the stars are shining a little brighter tonight because you're here.""",
  """Are you a magician? Every time I look at you, everyone else disappears.""",
  """If you were a song, you'd be a chart-topper.""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Do you have a Band-Aid? Because I just hurt myself falling for you.""",
  """Is it hot in here, or is it just the chemistry between us?""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Is your name Google? Because you're everything I've been searching for.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a vegetable, you'd be a cute-cumber.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """If beauty were time, you'd be an eternity.""",
  """Are you a troublemaker? Because you've got mischief in those eyes.""",
  """Did it hurt when you fell from heaven? Because you look devilishly good.""",
  """Is your name Wi-Fi? Because I'm really feeling a connection.""",
  """Do you have a mirror in your pocket? Because I can see myself in your pants.""",
  """Excuse me, but I think the stars are shining a little brighter tonight because you're here.""",
  """Are you a magician? Every time I look at you, everyone else disappears.""",
  """If you were a song, you'd be a chart-topper.""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Do you have a Band-Aid? Because I just hurt myself falling for you.""",
  """Is it hot in here, or is it just the chemistry between us?""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Is your name Google? Because you're everything I've been searching for.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a vegetable, you'd be a cute-cumber."""
];
