List<String> Cheesy = [
  """Forget love at first sight, I already love the sound of your name.""",
  """You're so sweet, I need insulin before even talking to you.""",
  """If I were a dictionary, "gorgeous" would be next to your name.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """I think I'm falling for you, and it's not gravity's fault. It's your amazing personality!""",
  """Did it hurt when you fell from heaven? Because you landed right on my heart.""",
  """My love for you is like a slice of pizza - cheesy, irresistible, and I can't get enough.""",
  """Is your name Google? Because you have everything I'm searching for.""",
  """You're like a warm summer breeze, making my heart flutter like a hummingbird's wings.""",
  """Your smile is sunshine after a storm, chasing away the clouds and lighting up my world.""",
  """If you were a melody, I'd be on repeat, forever lost in the symphony of your laughter."""
 """Do you work at a cheesecake factory? Because you're making me melt.""",
  """Are you made of cheese? Because you're nacho typical person.""",
  """If you were a fruit, you'd be a fineapple.""",
  """Are you a magician? Every time I look at you, everyone else disappears.""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Are you a parking ticket? Because you've got "Fine" written all over you.""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight.""",
  """Do you have a name, or can I call you mine?""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Is your name Chapstick? Because you're da balm!""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Do you have a name, or can I call you mine?""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
];
