List<String> Cute = [
  """If beauty were a crime, you'd be guilty as charged.""",
  """If cuteness were a currency, you'd be the richest person alive.""",
  """You make my heart do the cutest little tap dance, like butterflies at a flower festival.""",
  """There's a sunflower blooming in my chest just because you smiled at me.""",
  """You're the missing sprinkle on my cupcake, the rainbow after the rain, the cherry on top of everything cute.""",
  """I tripped over my own feet just trying to say hello. Is that clumsy enough to impress you?""",
  """They say love makes you clumsy, and judging by my heart doing double flips, I must be falling for you.""",
  """Warning: excessive smiling and blushing may occur when within your adorable orbit."""
      """Do you have a map? I keep getting lost in your adorable eyes.""",
  """Are you a time traveler? Because I see you in my future.""",
  """Can I borrow your smile? It's the cutest thing I've ever seen.""",
  """Are you a magician? Because whenever I'm with you, time stands still.""",
  """Is your name Wi-Fi? Because I'm really feeling a connection.""",
  """Can I take a picture of you to prove to my friends that angels exist?""",
  """Do you have a sunburn or are you always this hot?""",
  """You must be a campfire because you're hot and I want s'more.""",
  """Are you a banana? Because you make me go all mushy inside.""",
  """I'm not a photographer, but I can picture us together.""",
  """Do you have a Band-Aid? I just hurt myself falling for you.""",
  """Are you a puzzle? Because you're the missing piece of my life.""",
  """I must be a snowflake because I've fallen for you.""",
  """Are you a magician? Because every time I look at you, everyone else disappears.""",
  """If kisses were snowflakes, I'd send you a blizzard.""",
  """Is your name Google? Because you've got everything I've been searching for.""",
  """Do you have a name, or can I call you mine?""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Can I borrow a quarter? I want to call my mom and tell her I just met the girl of my dreams.""",
  """You must be a camera because every time I look at you, I smile.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Are you a cat? Because you're purr-fect.""",
  """Is there an airport nearby or is it my heart taking off because of you?""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """Are you a parking ticket? Because you've got "Fine" written all over you.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Are you a bank loan? Because you've got my interest.""",
  """If beauty were time, you'd be an eternity.""",
  """You're like a dictionary – you add meaning to my life.""",
  """Can I take a picture of you so I can show Santa what I want for Christmas?""",
  """You must be a ninja because you snuck into my heart.""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Is your name Google? Because you have everything I've been searching for.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Can I follow you home? Because my parents always told me to follow my dreams.""",
  """I must be a snowflake because I've fallen for you.""",
  """Are you a camera? Every time I look at you, I smile.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """You must be a parking ticket because you've got "Fine" written all over you.""",
  """If beauty were time, you'd be an eternity.""",
  """Can I borrow a quarter? I want to call my mom and tell her I just met the girl of my dreams.""",
  """If cuteness were a currency, you'd be the richest person alive.""",
  """Are you a time traveler? Because I see you in my future.""",
  """Can I take a picture of you to prove to my friends that angels exist?""",
  """Do you have a sunburn or are you always this hot?""",
  """Are you a magician? Because whenever I'm with you, time stands still.""",
  """If beauty were a crime, you'd be guilty as charged.""",
  """Is your name Wi-Fi? Because I'm really feeling a connection.""",
  """Can I borrow your smile? It's the cutest thing I've ever seen.""",
  """Are you a puzzle? Because you're the missing piece of my life.""",
  """I'm not a photographer, but I can picture us together.""",
  """Do you have a Band-Aid? I just hurt myself falling for you.""",
  """Are you a banana? Because you make me go all mushy inside.""",
  """I must be a snowflake because I've fallen for you.""",
  """Are you a magician? Because every time I look at you, everyone else disappears.""",
  """If kisses were snowflakes, I'd send you a blizzard.""",
  """Is your name Google? Because you've got everything I've been searching for.""",
  """Do you have a name, or can I call you mine?""",
];
