List<String> Dirty = [
  """Is your name Dirty? Because you've been running through my mind all day.""",
  """You must be a broom, 'cause you sweep me off my feet.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Is it hot in here or is it just our chemistry?""",
  """Are you an archaeologist? Because I've got a large bone for you to examine.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """If I were a cat, I'd spend all 9 lives with you.""",
  """Are you a magician? Whenever I look at you, everyone else disappears.""",
  """Is your name Google? Because you've got everything I've been searching for.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Can I take a picture of you so I can show Santa what I want for Christmas?""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Do you have a name, or can I call you mine?""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """Is your name detergent? Because you’ve got me feeling dirty and bubbly.""",
  """Are you a pirate? Because you can raise my Jolly Roger anytime.""",
  """Is there a rainbow today? I just found the treasure I've been searching for.""",
  """Is your name Cinderella? Because I see that dress disappearing at midnight.""",
  """Is your name Netflix? Because I could binge-watch you all night.""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Are you a thief? Because you stole my attention.""",
  """Is your name Google? Because you've got everything I've been searching for.""",
  """Can I follow you where you go? Because my parents always told me to follow my dreams.""",
  """Are you a magician? Because every time I look at you, everyone else disappears.""",
  """If I could rearrange the alphabet, I’d put U and I together.""",
  """Is there an airport nearby or is it my heart taking off?""",
  """Are you an interior decorator? Because when I saw you, the entire room became beautiful.""",
  """If beauty were sunlight, you'd shine from a million light-years away.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight."""
];
