List<String> Food = [
  """Forget coffee, you're the sugar rush that gets my heart racing and my brain buzzing""",
  """Are you a banana? Because I find you a-peeling.""",
  """Are you a microwave? Because you melt my heart.""",
  """Is your name Nutella? Because you're smooth, spreadable, and utterly irresistible.""",
  """If you were a vegetable, you'd be a cute-cumber.""",
  """Are you a pizza? Because you've got a pizza my heart.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Do you have a name, or can I call you mine?""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """Are you a dessert? Because you're sweeter than chocolate.""",
  """If you were a fruit, you'd be a fineapple.""",
  """Are you made of icing? Because you make everything better.""",
  """Is your name Starbucks? Because I like you a latte.""",
  """Are you a burger? Because you're a great catch.""",
  """Do you like tacos? Because you're nacho average person.""",
  """Is your name Olive? Because you've got me feeling extra virgin.""",
  """Are you a bakery? Because you've got buns of steel.""",
  """Are you a donut? Because you complete me.""",
  """Do you like breakfast? Because you're the syrup on my pancakes.""",
  """Are you a microwave? Because you melt my heart.""",
  """If you were a vegetable, you'd be a cute-cumber.""",
  """Are you a pizza? Because you've got a pizza my heart.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight."""
];
