List<String> Funny = [
  """Is your name Wi-Fi? 'Cause I'm feeling a strong connection.""",
  """Is your name Netflix? Because I could binge-watch you all day.""",
  """I'm like a good pun - cheesy, but you'll laugh anyway.""",
  """They say I'm a walking disaster, but hey, at least I'm entertaining.""",
  """On a scale of 1 to 10, you're a Google search for 'how to flirt without dying of awkwardness.'""",
  """If you were a fruit, you'd be a 'fine-apple'.""",
  """I just lost my phone number. Can I have yours?""",
  """Hey, if you ever need someone to blame for bad luck, I'm always happy to volunteer.""",
  """Are you the square root of -1? Because you're imaginary and perfect.""",
  """They say laughter is the best medicine, so are you single?""",
  """I'm allergic to cats, but you're so purrfect I might have to take the allergy meds.""",
  """Did you invent the airplane? Because you seem Wright for me.""",
  """My therapist says I should talk to new people, so... hi!""",
  """Are you a parking ticket? 'Cause you've got 'fine' written all over you.""",
  """Hey, I'm like a good book - full of chapters you haven't read yet.""",
  """If you were a vegetable, you'd be a 'cute-cumber'.""",
  """On a scale of 1 to 10, you're a 10 and I'm the decimal point hoping to make it to an 11.""",
  """I'm not lost, I'm just exploring alternative routes to your heart.""",
  """They say opposites attract, so if you're a walking disaster, then hi there!""",
  """Is your name Google Chrome? Because you're my default bae."""
      """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """If you were a vegetable, you’d be a cute-cumber!""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a fruit, you’d be a fineapple!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Are you a bank loan? Because you have my interest.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a triangle, you’d be acute one.""",
  """Is your name Wi-fi? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a time traveler? Because I can see you in my future!""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If you were a cat, you’d purr-fectly fit into my lap!""",
  """Are you French? Because Eiffel for you.""",
  """Do you have a sun map? Because you light up my world.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a name, or can I call you mine?""",
  """Are you a parking ticket? Because you’ve got "FINE" written all over you!""",
  """If you were a fruit, you’d be a fineapple!""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """Do you have a map? Because I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you’re Cu-Te.""",
  """Are you a campfire? Because you’re hot and I want s’more.""",
  """If you were a vegetable, you’d be a cutecumber!""",
  """Are you a Wi-Fi signal? Because I’m really feeling a connection.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If you were a triangle, you’d be acute one.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If you were a vegetable, you’d be a cutecumber!""",
];
