List<String> Motivational = [
  """If determination were a currency, you'd be a millionaire.""",
  """If life were a book, you'd be the most inspiring chapter.""",
  """They say aim for the stars, but with you, I reach for infinity.""",
  """Forget sparks, you ignite supernovae within me. Let's chase dreams bigger than the sky.""",
  """My heart used to be a compass, lost and spinning. Now, with you, it points north - towards our shared horizon.""",
  """Challenge accepted. You inspire me to be bolder, brighter, a masterpiece in the making.""",
  """Forget butterflies, you set my soul on fire. Ready to chase adventures that ignite the world?""",
  """They say the impossible takes time, but with you, it feels like a blink, a shared leap into the extraordinary.""",
  """My comfort zone feels small with you around. Let's paint the world with the colors of our wildest dreams.""",
  """Forget doubts, you fill me with the audacity to hope. Together, we can rewrite the stars, line by daring line.""",
  """My heart used to be a whisper, afraid to be heard. Now, with you, it roars a symphony, an anthem to our limitless potential.""",
  """They say fear holds us back, but you fuel my courage. Ready to conquer mountains, hand in hand, hearts overflowing with fire?"""
      """Do you have a compass? Because you always point me in the right direction.""",
  """Are you a magnet? Because you attract success.""",
  """If success were a race, I'd want you as my running mate.""",
  """Do you have a map? Because you've charted a course for greatness.""",
  """Do you have a mirror? Because I see a champion in you.""",
  """If positivity were gold, you'd own the biggest treasure.""",
  """Are you a lighthouse? Because you guide others through the storm.""",
  """If hard work were a language, you'd be fluent.""",
  """Do you have a toolkit? Because you're the embodiment of resilience.""",
  """If inspiration were a painting, you'd be the masterpiece.""",
  """Are you a star? Because your determination shines brightly.""",
  """If success were a ladder, you'd be climbing it effortlessly.""",
  """Do you have a trophy? Because you embody achievement.""",
  """If passion were fuel, you'd be unstoppable.""",
  """Are you a beacon? Because you light up the path to success.""",
  """If dedication were a song, you'd be the melody.""",
  """Do you have a compass? Because you always lead by example.""",
  """If confidence were a superpower, you'd be invincible.""",
  """Are you a catalyst? Because you spark motivation in others.""",
  """If ambition were a destination, you'd already be there.""",
  """Do you have a guidebook? Because you navigate challenges with grace.""",
  """If positivity were a language, you'd be fluent.""",
  """Are you a role model? Because you inspire greatness in everyone.""",
  """If perseverance were an art form, you'd be a masterpiece.""",
  """Do you have a beacon? Because you illuminate the path to success.""",
  """If motivation were a crown, you'd be royalty.""",
  """Are you a flame? Because your passion ignites others.""",
  """If success were a symphony, you'd be the conductor.""",
  """Do you have a compass? Because you always point towards progress.""",
  """If courage were a muscle, yours would be the strongest.""",
  """Are you a sunrise? Because you bring hope and inspiration.""",
  """If dedication were a recipe, you'd be the secret ingredient.""",
  """Do you have a compass? Because you navigate life's challenges effortlessly.""",
  """If determination were a color, you'd paint the world.""",
  """Are you a guide? Because you lead with wisdom and encouragement.""",
  """If success were a story, you'd be the protagonist.""",
  """Do you have a torch? Because you light the way for others.""",
  """If resilience were a shield, yours would be indestructible.""",
  """Are you an inspiration? Because you motivate even in the darkest times.""",
  """If motivation were a melody, you'd be music to my ears.""",
  """Do you have a compass? Because you always find your way to success.""",
  """If courage were a currency, you'd be the richest person alive.""",
  """Are you a mentor? Because you guide others to their best selves.""",
  """If determination were a mountain, you'd reach the summit.""",
  """Do you have a compass? Because your path leads to achievement.""",
  """If success were a painting, you'd be the masterpiece.""",
  """Are you a beacon of hope? Because you inspire even in adversity.""",
  """If perseverance were a virtue, you'd be its embodiment.""",
  """Do you have a compass? Because you navigate challenges like a pro.""",
  """If motivation were a star, you'd be the brightest in the sky.""",
  """Are you a compass? Because you always point toward success.""",
  """If courage were a crown, you'd wear it majestically.""",
  """Do you have a torch? Because you light the way for others.""",
  """If determination were a book, you'd be the bestseller.""",
  """Are you an inspiration? Because you fuel ambition in others.""",
  """If success were a melody, you'd be the sweetest tune.""",
  """Do you have a compass? Because your direction leads to triumph.""",
  """If perseverance were a song, you'd be the anthem.""",
  """Are you a beacon? Because you shine through life's challenges.""",
  """If motivation were a currency, you'd be the wealthiest.""",
  """Do you have a compass? Because your path leads to victory.""",
  """If courage were a guidebook, you'd write the chapters.""",
  """Are you a spark? Because you ignite the fire of determination.""",
  """If dedication were a beacon, you'd be its brightest light.""",
  """Do you have a compass? Because you navigate through obstacles.""",
  """If motivation were a flame, you'd be an eternal fire.""",
  """Are you a guiding star? Because you lead others to success.""",
  """If success were a canvas, you'd paint the most vibrant picture.""",
  """Do you have a compass? Because you always find your way to success.""",
  """If courage were a virtue, you'd exemplify it.""",
  """Are you a mentor? Because you shape futures with your wisdom.""",
  """If determination were a mountain, you'd conquer its peaks.""",
  """Do you have a compass? Because your direction leads to achievement.""",
  """If success were a tapestry, you'd weave the brightest threads.""",
  """Are you a beacon of hope? Because you shine brightest in tough times.""",
  """If perseverance were a virtue, you'd epitomize it.""",
  """Do you have a compass? Because you navigate challenges effortlessly.""",
  """If motivation were a star, you'd be the brightest in the sky.""",
  """Are you a compass? Because you always point toward success.""",
  """If courage were a crown, you'd wear it majestically.""",
  """Do you have a torch? Because you light the way for others.""",
  """If determination were a book, you'd be the bestseller.""",
  """Are you an inspiration? Because you fuel ambition in others.""",
  """If success were a melody, you'd be the sweetest tune.""",
  """Do you have a compass? Because your direction leads to triumph.""",
  """If perseverance were a song, you'd be the anthem.""",
  """Are you a beacon? Because you shine through life's challenges.""",
  """If motivation were a currency, you'd be the wealthiest.""",
  """Do you have a compass? Because your path leads to victory.""",
  """If courage were a guidebook, you'd write the chapters.""",
  """Are you a spark? Because you ignite the fire of determination.""",
  """If dedication were a beacon, you'd be its brightest light.""",
  """Do you have a compass? Because you navigate through obstacles.""",
  """If motivation were a flame, you'd be an eternal fire.""",
  """Are you a guiding star? Because you lead others to success.""",
  """If success were a canvas, you'd paint the most vibrant picture.""",
  """Do you have a compass? Because you always find your way to success.""",
  """If courage were a virtue, you'd exemplify it.""",
  """Are you a mentor? Because you shape futures with your wisdom.""",
  """If determination were a mountain, you'd conquer its peaks.""",
  """Do you have a compass? Because your direction leads to achievement.""",
  """If success were a tapestry, you'd weave the brightest threads.""",
  """Are you a beacon of hope? Because you shine brightest in tough times.""",
  """If perseverance were a virtue, you'd epitomize it.""",
  """Do you have a compass? Because you navigate challenges effortlessly.""",
  """If motivation were a star, you'd be the brightest in the sky.""",
  """Are you a compass? Because you always point toward success.""",
  """If courage were a crown, you'd wear it majestically."""
];
