List<String> Nerd = [
  """Are you a 90-degree angle? Because you're looking right.""",
  """Is your name Google? Because you have everything I’ve been searching for.""",
  """If you were a triangle, you'd be acute one.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """I'm not a weatherman, but you can expect more than a few inches tonight.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Do you have a name, or can I call you mine?""",
  """Is your name Chapstick? Because you're da balm!""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """I must be a snowflake because I've fallen for you.""",
  """I'm not a genie, but I can make your dreams come true.""",
  """Is your name Ariel? Because we mermaid for each other.""",
  """Are you a keyboard? Because you're just my type.""",
  """Do you like Star Wars? Because Yoda one for me!""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Are you a carbon sample? Because I want to date you.""",
  """Are you a time traveler? Because I see you in my future.""",
  """Is your name Wi-fi? Because I'm feeling a connection.""",
  """Are you the square root of -1? Because you can't be real, but here you are.""",
  """Are you a camera? Every time I look at you, I smile.""",
  """Do you have 11 protons? Because you're sodium fine.""",
  """If you were a triangle, you'd be acute one.""",
  """Is your name Google? Because you have everything I’ve been searching for."""
];
