List<String> Romantic = [
  """Your lips are made to be kissed. Let’s not let them be wasted.""",
  """My lips hurt, wanna kiss them and make them better?""",
  """Smiling at you feels like sunshine on a book page - warm, illuminating, and whispering stories.""",
  """My heart used to be a compass, always north. Now it spins like a galaxy, lost in your gravitational pull.""",
  """They say love is blind, but you painted constellations in my soul with a single glance.""",
  """Forget fairytales, you're my happily ever after, chapter by stolen smile, verse by whisper in the night.""",
  """Coffee is my fuel, but your laugh is my supernova. One ignites, the other ignites galaxies.""",
  """Is this a dream? Because falling for you feels like waking up to fireworks, every single morning.""",
  """Words stumble when trying to describe you. The closest I can get? Breathtakingly beautiful, hopelessly smitten.""",
  """You have a secret smile that unlocks galaxies within me. May I explore the cosmos in your eyes?""",
  """Silence with you isn't awkward, it's a symphony of unspoken promises and shared dreams.""",
  """I used to fear the dark, but then you held my hand. Now, shadows dance and stardust shimmers in your wake.""",
  """Butterflies? You ignite aviaries in my stomach. A kaleidoscope of emotions with every glance, every whisper.""",
  """Forever sounds daunting, but with you, it feels like a cozy blanket, warm and endless.""",
  """You're the missing piece I never knew I craved. A melody to my soul, a lighthouse in my storm.""",
  """They say love is blind, but your laughter paints rainbows across my heart, vivid and forevermore.""",
  """Forget the stars, you're the galaxy I get lost in, willingly, breathlessly, completely."""
      """Are you a magician? Because whenever I look at you, everyone else disappears.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """Are you a camera? Because every time I look at you, I smile.""",
  """If kisses were snowflakes, I'd send you a blizzard.""",
  """Is your name Google? Because you have everything I've been searching for.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If love were a storybook, we’d meet on the very first page.""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """If I were a cat, I'd spend all 9 lives with you.""",
  """I must be a snowflake because I've fallen for you.""",
  """Is your name Wi-fi? Because I'm really feeling a connection.""",
  """If beauty were time, you'd be eternity.""",
  """You must be a campfire because you're hot and I want s'more.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """If happiness was a drop, I'd send you an ocean.""",
  """Do you have a sunburn, or are you always this hot?""",
  """Is there an airport nearby or is it my heart taking off?""",
  """You're like a fine wine. The more I get to know you, the better you get.""",
  """If love were a song, I'd play it in your favorite key.""",
  """Can I borrow a quarter? I want to call my mom and tell her I just met the love of my life.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """You must be a candle because you light up the room.""",
  """I must be a snowflake because I've fallen for you.""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If beauty were a crime, you'd be serving a life sentence.""",
  """Do you have a name, or can I call you mine?""",
  """If you were a vegetable, you’d be a cutecumber.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """You're so sweet, you could put Hershey's out of business.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """If love were a rose, I'd pick you every time.""",
  """Is your name Google? Because you've got everything I'm searching for.""",
  """If you were a triangle, you'd be acute one.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a vegetable, you’d be a cutecumber.""",
  """Are you a bank loan? Because you've got my interest.""",
  """Is your name Wi-fi? Because I'm feeling a connection.""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If I could rearrange the alphabet, I'd put U and I together.""",
  """Is there an airport nearby or is it my heart taking off?""",
  """You must be a magician because whenever I look at you, everyone else disappears.""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Do you have a name, or can I call you mine?""",
  """If love were a song, I'd play it in your favorite key.""",
  """If beauty were time, you'd be eternity.""",
  """I must be a snowflake because I've fallen for you.""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If happiness was a drop, I'd send you an ocean.""",
  """Can I borrow a quarter? I want to call my mom and tell her I just met the love of my life.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """You must be a candle because you light up the room.""",
  """I must be a snowflake because I've fallen for you.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """You're so sweet, you could put Hershey's out of business.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """If love were a rose, I'd pick you every time.""",
  """Is your name Google? Because you've got everything I'm searching for.""",
  """If you were a triangle, you'd be acute one.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a vegetable, you’d be a cutecumber.""",
  """Are you a bank loan? Because you've got my interest.""",
  """Is your name Wi-fi? Because I'm feeling a connection.""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If I could rearrange the alphabet, I'd put U and I together.""",
  """Is there an airport nearby or is it my heart taking off?""",
  """You must be a magician because whenever I look at you, everyone else disappears.""",
  """If you were a vegetable, you'd be a cutecumber.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """Are you made of copper and tellurium? Because you're Cu-Te.""",
  """Do you have a name, or can I call you mine?""",
  """If love were a song, I'd play it in your favorite key.""",
  """If beauty were time, you'd be eternity.""",
  """I must be a snowflake because I've fallen for you.""",
  """Do you have a pencil? Cause I want to erase your past and write our future.""",
  """If happiness was a drop, I'd send you an ocean.""",
  """Can I borrow a quarter? I want to call my mom and tell her I just met the love of my life.""",
  """I'm not a photographer, but I can definitely picture us together.""",
  """You must be a candle because you light up the room.""",
  """I must be a snowflake because I've fallen for you.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """You're so sweet, you could put Hershey's out of business.""",
  """Do you have a map? I keep getting lost in your eyes.""",
  """If love were a rose, I'd pick you every time.""",
  """Is your name Google? Because you've got everything I'm searching for.""",
  """If you were a triangle, you'd be acute one.""",
  """Do you have a sunburn, or are you always this hot?""",
  """If you were a vegetable, you’d be a cutecumber.""",
  """Are you a bank loan? Because you've got my interest.""",
  """Is your name Wi-fi? Because I'm feeling a connection.""",
  """Do you believe in love at first sight, or should I walk by again?""",
  """Are you a campfire? Because you're hot and I want s'more.""",
  """Do you have a Band-Aid? Because I just scraped my knee falling for you.""",
  """If I could rearrange the alphabet, I'd put U and I together.""",
  """Is there an airport nearby or is it my heart taking off?""",
  """You must be a magician because whenever I look at you, everyone else disappears."""
];
